Kodilla Module 8.4
radoslaw-lazur/radoslaw-lazur-kodilla-java pull request #18
Opened 2019-08-22 21:52 UTC by radoslaw-lazur

Task in package com.kodilla.exception.test in main

2019-08-23 16:36 UTC, MARudnicki requested changes

2019-08-23 16:36 UTC, MARudnicki commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightSearch.java
> +                .filter(entry -> entry.getValue() == true)
wystarczy 
`.filter(entry -> entry.getValue())`

2019-08-23 16:36 UTC, MARudnicki commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightSearch.java
> +                .count();
w tej konstrukcji nie wykorzystujesz zalet hashmapy, tylko iterujesz po kolejnych elementach.
Sa tutaj 3 opcje: lotnisko istnieje i jest dostepne -> zwracasz true
istnieje i NIE jest dostepne -> zwracasz false //brakuje tej opcji
nie istnieje -> wyjatek

2019-08-23 16:36 UTC, MARudnicki commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightSearch.java
> +                .count();
mozesz np zapisac
boolean airportExists = flights.containsKey(flight.getArrivalAirport());
boolean isAvailable = flights.get(flight.getArrivalAirport());

2019-08-24 07:24 UTC, MARudnicki requested changes

2019-08-24 07:24 UTC, MARudnicki commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightSearch.java
>          }
Zapisz prosciej
```
        if (!flights.containsKey(flight.getArrivalAirport())) {
            throw new RouteNotFoundException();
        }
        return flights.get(flight.getArrivalAirport());
```

2019-08-24 08:50 UTC, radoslaw-lazur commented on kodilla-exception/src/main/java/com/kodilla/exception/test/FlightSearch.java
>          }
O kurde, ale krótki zapis

2019-08-24 18:08 UTC, merged